[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

# Verbosity for `forge script` via -vvv
[profile.ci]
fuzz = { runs = 256 }

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
